/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encodeStateAsUpdate(doc: Doc, state?: Buffer | undefined | null): Buffer
export declare function encodeStateVector(doc: Doc): Buffer
export declare function compareStructStores(store: YStore, other: YStore): boolean
export declare function compareIds(a?: YId | undefined | null, b?: YId | undefined | null): boolean
export declare function createDeleteSetFromStructStore(store: YStore): YDeleteSet
export declare function equalDeleteSets(a: YDeleteSet, b: YDeleteSet): boolean
export declare function snapshot(doc: Doc): YSnapshot
export declare function encodeSnapshot(snapshot: YSnapshot): Buffer
export declare function applyUpdate(doc: Doc, update: Buffer): void
export declare function mergeUpdates(updates: Array<Buffer>): Buffer
export declare function isAbstractType(unknown: unknown): boolean
export class YArray {
  get length(): number
  get isEmpty(): boolean
  get<T = unknown>(index: number): T
  slice<T = unknown>(start: number, end?: number | undefined | null): Array<T>
  map<T = unknown>(callback: (...args: any[]) => any): Array<T>
  insert(index: number, value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  push(value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  unshift(value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  delete(index: number, len?: number | undefined | null): void
  iter(): YArrayIterator
  toArray(): JsArray
  toJSON(): JsArray
  observe(callback: (...args: any[]) => any): void
  observeDeep(callback: (...args: any[]) => any): void
}
export class YArrayIterator {
  [Symbol.iterator](): Iterator<MixedYType, void, number | undefined | null>
}
export type YAwareness = Awareness
export class Awareness {
  constructor(clientId?: number | undefined | null)
  get clientId(): number
  get states<T = Record<string, any>>(): Record<string, T>
}
export type YDoc = Doc
export class Doc {
  constructor(clientId?: number | undefined | null)
  get clientId(): number
  set clientId(clientId: number)
  get guid(): string
  get store(): YStore
  get keys(): Array<string>
  getOrCreateArray(key: string): YArray
  getOrCreateText(key: string): YText
  getOrCreateMap(key: string): YMap
  createArray(): YArray
  createText(text?: string | undefined | null): YText
  createMap(entries?: JsArray | undefined | null): YMap
  applyUpdate(update: Buffer): void
  encodeStateAsUpdateV1(state?: Buffer | undefined | null): Buffer
  gc(): void
  onUpdate(callback: (result: Uint8Array) => void): void
  transact(callback: (...args: any[]) => any): void
}
export class YMap {
  get length(): number
  get size(): number
  get isEmpty(): boolean
  get itemId(): YId | null
  get<T = unknown>(key: string): T
  set<T = YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined>(key: string, value: T): T
  delete(key: string): void
  clear(): void
  toJson(): object
  entries(): YMapEntriesIterator
  keys(): YMapKeyIterator
  values(): YMapValuesIterator
  observe(callback: (...args: any[]) => any): void
  observeDeep(callback: (...args: any[]) => any): void
}
export class YMapEntriesIterator {
  [Symbol.iterator](): Iterator<JsArray, void, number | undefined | null>
}
export class YMapKeyIterator {
  [Symbol.iterator](): Iterator<string, void, number | undefined | null>
}
export class YMapValuesIterator {
  [Symbol.iterator](): Iterator<unknown, void, number | undefined | null>
}
export class YText {
  constructor()
  get len(): number
  get isEmpty(): boolean
  insert(index: number, str: string): void
  delete(index: number, len: number): void
  get length(): number
  applyDelta(delta: JsArray): void
  toDelta(): JsArray
  toString(): string
  observe(callback: (...args: any[]) => any): void
  observeDeep(callback: (...args: any[]) => any): void
}
export type YId = Id
export class Id { }
export type YStore = Store
export class Store { }
export type YDeleteSet = DeleteSet
export class DeleteSet { }
export class YSnapshot { }
