/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type YArray = Array
export class Array {
  constructor()
  get length(): number
  get isEmpty(): boolean
  get<T = unknown>(index: number): T
  slice<T = unknown>(start: number, end: number): Array<T>
  map<T = unknown>(callback: (...args: any[]) => any): Array<T>
  insert(index: number, value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  push(value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  unshift(value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  delete(index: number, len: number): void
  toJson(): JsArray
}
export type YDoc = Doc
export class Doc {
  constructor(clientId?: number | undefined | null)
  get clientId(): number
  get guid(): string
  get keys(): Array<string>
  getOrCreateArray(key: string): Array
  getOrCreateText(key: string): YText
  getOrCreateMap(key: string): YMap
  createArray(): Array
  createText(): YText
  createMap(): YMap
  applyUpdate(update: Buffer): void
  encodeStateAsUpdateV1(state?: Buffer | undefined | null): Buffer
  gc(): void
  onUpdate(callback: (result: Uint8Array) => void): void
}
export type YMap = Map
export class Map {
  constructor()
  get length(): number
  get isEmpty(): boolean
  get<T = unknown>(key: string): T
  set(key: string, value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  remove(key: string): void
  toJson(): object
}
export type YText = Text
export class Text {
  constructor()
  get len(): number
  get isEmpty(): boolean
  insert(index: number, str: string): void
  remove(index: number, len: number): void
  get length(): number
  toString(): string
}
