/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class YArray {
  constructor()
  get length(): number
  get isEmpty(): boolean
  get<T = unknown>(index: number): T
  insert(index: number, value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  remove(index: number, len: number): void
  toJson(): JsArray
}
export class Doc {
  constructor(clientId?: number | undefined | null)
  get clientId(): number
  get guid(): string
  get keys(): Array<string>
  getOrCreateArray(key: string): YArray
  getOrCreateText(key: string): YText
  getOrCreateMap(key: string): YMap
  createArray(): YArray
  createText(): YText
  createMap(): YMap
  applyUpdate(update: Buffer): void
  encodeStateAsUpdateV1(state?: Buffer | undefined | null): Buffer
  gc(): void
  onUpdate(callback: (result: Uint8Array) => void): void
}
export class YMap {
  constructor()
  get length(): number
  get isEmpty(): boolean
  get<T = unknown>(key: string): T
  set(key: string, value: YArray | YMap | YText | boolean | number | string | Record<string, any> | null | undefined): void
  remove(key: string): void
  toJson(): object
}
export class YText {
  constructor()
  get len(): number
  get isEmpty(): boolean
  insert(index: number, str: string): void
  remove(index: number, len: number): void
  get length(): number
  toString(): string
}
