name: ClusterFuzzLite cron tasks

on:
  workflow_dispatch:
  schedule:
    - cron: "43 19 * * *"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pruning:
    name: corpus pruning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: "prune"

  coverage:
    name: coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: coverage

      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: "coverage"
          sanitizer: coverage
